import warnings
import xarray as xr

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score

def eval_predictive_performance(
        idata,
        y_true=None,
        y_pred_prob=None,
        stats_by_chain=True,
        decision_threshold=0.5,
        compare_against_baseline=True,
        use_timed_average_baseline=False,
        alternative_baseline_predictions=None
    ):
    """
    Evaluate the predictive performance of a fitted model using posterior
    predictions and optionally compare performance against a baseline
    predictor.

    Note
    ---- 
    The function displays accuracy, precision, recall, F1-score, and ROC AUC
    from aggregated posterior predictions across chains and draws.

    By default, this function evaluates performance on on the observed
    data used for model fitting (`idata.observed_data["y"]`). To evaluate
    performance on independent data, provide target values as `y_true` and/or
    and corresponding predicted probabilities through `y_pred_prob`.
    
    Optionally, the function evaluates model performance against a baseline
    predictor. By default, the baseline is constructed from the average observed
    response probability for each item. A custom baseline can be provided using
    `alternative_baseline_predictions`.

    Additionally, the function evaluates the consistency of model performance
    across individual MCMC chains by reporting per-chain metrics and the
    maximum deviation between chains. This can be used to assess whether
    predictive performance is stable across posterior sampling chains.

    Parameters
    ----------
    idata : arviz.InferenceData
        ArviZ inference data object containing the fitted model results.
        Expected groups:
            - `observed_data["y"]`: observed binary response data.
            - `posterior["p"]`: posterior draws of predicted response
              probabilities.

    y_true : array-like, optional
        Binary ground-truth response values used for evaluation. If None,
        the observed responses are extracted from `idata.observed_data["y"]`.
        Providing external labels allows evaluation on validation or test data.

        Missing values are automatically excluded together with their
        corresponding predictions.

     y_pred_prob : array-like, optional
        Predicted probabilities used for evaluation. If None, posterior
        predictive probabilities are extracted from `idata.posterior["p"]`
        and averaged across chains and draws.

        Passing your own y_pred_prob allows evaluation of predictions generated
        from external validation or test datasets.

        It is assumed that passed y_pred_prob has no chain dimensions. Hence, chain
        comparison will be skipped.

    stats_by_chain : bool, default=True
        If True, compute and display predictive metrics separately for each
        posterior sampling chain (when multiple chains are available) and
        report consistency across chains.

    decision_threshold : float, default=0.5
        Probability threshold used to convert posterior predicted probabilities
        into binary class predictions.

    compare_against_baseline : bool, default=True
        If True, compute and display predictive performance metrics for a
        baseline predictor in addition to the fitted model.

    alternative_baseline_predictions : array-like, optional
        Custom baseline predictions used for comparison. Can contain either:
            - float values representing predicted probabilities (preferred), or
            - integer values representing binary predictions.

        If None, a baseline prediction is generated by using the average
        observed response probability for each item.

    Returns
    -------
    tuple
        A tuple containing:
            - accuracy:
                Classification accuracy.
            - precision:
                Precision score.
            - recall:
                Recall score.
            - f1:
                F1-score.
            - auc:
                ROC AUC score based on posterior predicted probabilities.
    """

    if not 0 <= decision_threshold <= 1:
        raise ValueError("`decision_threshold` must be between 0 and 1.")

    if y_true is None:
        y_true = idata.observed_data["y"].values[:, :, :].ravel()

    y_pred_prob_provided = y_pred_prob is not None
    if not y_pred_prob_provided:
        # taking the mean over all chains and all draws
        y_pred_prob = idata.posterior["p"].values[:,:,:,:,:].mean(axis=(0, 1), dtype=np.float64).ravel()

    if y_true.shape != y_pred_prob.shape:
        raise ValueError(
            f"`y_true` and `y_pred_prob` must have the same shape; "
            f"got {y_true.shape} and {y_pred_prob.shape}."
        )

    if np.isnan(y_pred_prob).any():
        raise ValueError(
            f"`y_pred_prob` cannot have NaN values."
        )

    nan_mask = np.isnan(y_true)
    if nan_mask.any():
        warnings.warn(
            "y_true data contains missing values; these data are excluded "
            "in both y_true and posterior predictions."
        )
        y_true = y_true[~nan_mask]
        y_pred_prob = y_pred_prob[~nan_mask]

    # Binary predictions
    y_pred = (y_pred_prob >= decision_threshold).astype(int)


    # Metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    auc = roc_auc_score(y_true, y_pred_prob)

    print(f"Accuracy : {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall   : {recall:.2f}")
    print(f"F1-score : {f1:.2f}")
    print(f"ROC AUC  : {auc:.2f}")

    print("\nConfusion matrix:")
    print(confusion_matrix(y_true, y_pred))

    # Metrics for the baseline
    if compare_against_baseline:

        # first construct baseline
        y_baseline_pred_prob = None
        if alternative_baseline_predictions is not None:
            y_baseline_pred_prob = np.asarray(alternative_baseline_predictions)
            y_baseline_pred = (y_baseline_pred_prob >= decision_threshold).astype(int)
        else:
            # use an average model as default baseline 
            n_items = idata.posterior.coords["item"].size
            n_timesteps = idata.posterior.coords["time"].size

            # baseline1: prevalence continually
            averaged_trajectory = np.zeros(0)
            for item in range(0, n_items):
                item_prevalence = np.nanmean(idata.observed_data["y"].values[:,item,:], axis=(0,1), dtype=np.float64)
                averaged_trajectory = np.concatenate([averaged_trajectory, np.repeat(item_prevalence, n_timesteps)])

            y_baseline_pred_prob = np.broadcast_to(
                averaged_trajectory,
                (idata.observed_data.sizes["person"], n_timesteps*n_items)
            ).ravel()

            # baseline2: prevalence continually, binarized
            if False:
                y_baseline_pred_prob = np.broadcast_to(
                    (averaged_trajectory >= 0.5).astype(int),
                    (idata.observed_data.sizes["person"], n_timesteps*n_items)
                ).ravel()

            # baseline3: average item probabilities over all (persons * item) cells
            averaged_trajectory = np.nanmean(idata.observed_data["y"].values, axis=0, dtype=np.float64).ravel()

            if use_timed_average_baseline:
                y_baseline_pred_prob = np.broadcast_to(
                    averaged_trajectory,
                    (idata.observed_data.sizes["person"], n_timesteps*n_items)
                ).ravel()            


        y_baseline_pred_prob = y_baseline_pred_prob[~nan_mask]
        y_baseline_pred = (y_baseline_pred_prob >= decision_threshold).astype(int)

        print("\nPerformance of the average model:")

        # Metrics
        baseline_accuracy = accuracy_score(y_true, y_baseline_pred)
        baseline_precision = precision_score(y_true, y_baseline_pred, zero_division=0)
        baseline_recall = recall_score(y_true, y_baseline_pred, zero_division=0)
        baseline_f1 = f1_score(y_true, y_baseline_pred, zero_division=0)
        
        print(f"Accuracy : {baseline_accuracy:.2f}")
        print(f"Precision: {baseline_precision:.2f}")
        print(f"Recall   : {baseline_recall:.2f}")
        print(f"F1-score : {baseline_f1:.2f}")
        if y_baseline_pred_prob is not None:
            baseline_auc = roc_auc_score(y_true, y_baseline_pred_prob)
            print(f"ROC AUC  : {baseline_auc:.2f}")

        print("\nConfusion matrix:")
        print(confusion_matrix(y_true, y_baseline_pred))


    # calculate metric consistency over chains
    if stats_by_chain and not y_pred_prob_provided:
        print("\nMetric consistency over chains:")
        if idata.posterior.coords.sizes["chain"] > 1:
            aucs_by_chain, accuracy_by_chain, precision_by_chain, recall_by_chain, f1_by_chain = [], [], [], [], []

            for chain in range(0, idata.posterior.coords.sizes["chain"]):
                y_pred_prob = idata.posterior["p"].isel(chain=chain).mean(dim=("draw"), dtype=np.float64).to_numpy().ravel()
                y_pred_prob = y_pred_prob[~nan_mask]
                y_pred = (y_pred_prob >= decision_threshold).astype(int)
                chain_auc = roc_auc_score(y_true, y_pred_prob)
                aucs_by_chain.append(chain_auc)
                chain_accuracy = accuracy_score(y_true, y_pred)
                accuracy_by_chain.append(chain_accuracy)
                chain_precision = precision_score(y_true, y_pred, zero_division=0)
                precision_by_chain.append(chain_precision)
                chain_recall = recall_score(y_true, y_pred, zero_division=0)
                recall_by_chain.append(chain_recall)
                chain_f1 = f1_score(y_true, y_pred, zero_division=0)
                f1_by_chain.append(chain_f1)
                
                print(f"\t[chain {str(chain).rjust(2)}] ROC AUC: {auc:.2f}; Accuracy: {accuracy:.2f}; Precision: {precision:.2f}; Recall: {recall:.2f}; F1: {f1:.2f}")
            
            print(f"Maximum Deviation:\n\tROC AUC: {(max(aucs_by_chain) - min(aucs_by_chain)):.2f}; "
                +f"Accuracy: {(max(accuracy_by_chain) - min(accuracy_by_chain)):.2f} "
                +f"Precision: {(max(precision_by_chain) - min(precision_by_chain)):.2f} "
                +f"Recall: {(max(recall_by_chain) - min(recall_by_chain)):.2f} "
                +f"F1: {(max(f1_by_chain) - min(f1_by_chain)):.2f}")
        else:
            print("\tOnly one chain available: skipping metrics over chains.")

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "auc": auc
    }


def eval_predictive_performance_from_svi_params(
        posterior_medians,
        posterior_quantiles,
        y_true, # (person, item, time)
        decision_threshold=0.5
    ):
    """ Evaluate predictive performance of a 2PL model fitted using SVI.
    Computes binary classification and ranking metrics from posterior
    predictions calculated via parameters obtained from the fitted SVI guide.
    Missing observations in `y_true` are excluded from evaluation.
    
    Parameters
    ----------
    posterior_medians TODO

    posterior_quantiles TODO
    
    y_true : numpy.ndarray
    Observed binary outcomes with shape (person, item, time). Missing
    values (NaN) are excluded from metric calculations.
    
    decision_threshold : float, default=0.5
    Probability threshold used to convert predicted probabilities into
    binary predictions.
    
    Returns
    -------
    dict
    Dictionary containing accuracy, precision, recall, F1 score, and
    ROC AUC for the posterior-median predictions, together with
    corresponding lower and upper predictive-bound metrics.
    
    Raises
    ------
    ValueError
    If `y_true` is None, its shape does not match the predicted
    probabilities, or the posterior predictions contain NaN values.
    
    Notes
    -----
    The lower and upper predictive-bound metrics are obtained by
    thresholding the lower and upper posterior predictive probability
    bounds, respectively. These should not be interpreted as formal
    credible intervals for the performance metrics themselves.
    """

    if not 0 <= decision_threshold <= 1:
        raise ValueError("`decision_threshold` must be between 0 and 1.")

    if y_true is None:
        raise ValueError("`y_true` cannot be None")

    nan_mask = np.isnan(y_true.ravel())
    if not np.all(np.isin(np.unique(y_true.ravel()[~nan_mask]), [0, 1])):
        raise ValueError(
            f"`y_true` must contain only 0/1 values."
        )

    # (chain, draw, person, item, time)
    # yields (person, item, time)
    y_pred_probs_medians = get_predictions_from_samples_2PL_(posterior_medians)[0][0]

    # (chain, draw, person, item, time)
    # yields (person, item, time)
    y_pred_probs_ci_lower = get_predictions_from_samples_2PL_(
            {k: v[0] for k,v in posterior_quantiles.items()}
        )[0][0]

    y_pred_probs_ci_upper = get_predictions_from_samples_2PL_(
            {k: v[1] for k,v in posterior_quantiles.items()}
        )[0][0]

    if y_true.shape != y_pred_probs_medians.shape:
        raise ValueError(
            f"`y_true` and `y_pred_prob` must have the same shape; "
            f"got {y_true.shape} and {y_pred_probs_medians.shape}."
        )

    if np.isnan(y_pred_probs_medians).any():
        raise ValueError(
            f"`y_pred_prob` cannot have NaN values."
        )

    if np.isnan(y_pred_probs_ci_lower).any():
        raise ValueError(
            f"`y_pred_prob` cannot have NaN values."
        )

    if np.isnan(y_pred_probs_ci_upper).any():
        raise ValueError(
            f"`y_pred_prob` cannot have NaN values."
        )

    nan_mask = np.isnan(y_true)
    if nan_mask.any():
        warnings.warn(
            "y_true data contains missing values; these data are excluded "
            "in both y_true and posterior predictions."
        )
        y_true = y_true[~nan_mask]
        y_pred_probs_medians = y_pred_probs_medians[~nan_mask]
        y_pred_probs_ci_lower = y_pred_probs_ci_lower[~nan_mask]
        y_pred_probs_ci_upper = y_pred_probs_ci_upper[~nan_mask]


    # Binary predictions
    y_pred_medians  = (y_pred_probs_medians  >= decision_threshold).astype(int)
    y_pred_ci_lower = (y_pred_probs_ci_lower >= decision_threshold).astype(int)
    y_pred_ci_upper = (y_pred_probs_ci_upper >= decision_threshold).astype(int)


    # Metrics
    accuracy_medians = accuracy_score(y_true, y_pred_medians)
    accuracy_ci_lower = accuracy_score(y_true, y_pred_ci_lower)
    accuracy_ci_upper = accuracy_score(y_true, y_pred_ci_upper)
    precision_medians = precision_score(y_true, y_pred_medians, zero_division=0)
    precision_ci_lower = precision_score(y_true, y_pred_ci_lower, zero_division=0)
    precision_ci_upper = precision_score(y_true, y_pred_ci_upper, zero_division=0)
    recall_medians = recall_score(y_true, y_pred_medians, zero_division=0)
    recall_ci_lower = recall_score(y_true, y_pred_ci_lower, zero_division=0)
    recall_ci_upper = recall_score(y_true, y_pred_ci_upper, zero_division=0)
    f1_medians = f1_score(y_true, y_pred_medians, zero_division=0)
    f1_ci_lower = f1_score(y_true, y_pred_ci_lower, zero_division=0)
    f1_ci_upper = f1_score(y_true, y_pred_ci_upper, zero_division=0)
    auc_medians = roc_auc_score(y_true, y_pred_probs_medians)
    auc_ci_lower = roc_auc_score(y_true, y_pred_probs_ci_lower)
    auc_ci_upper = roc_auc_score(y_true, y_pred_probs_ci_upper)


    print("! Note !\n--------\n`lower` and `upper` bounds are defined by lower and upper",
          "bounds of the model parameters not the posterior predictions.")

    print(f"Accuracy : {accuracy_medians:.2f}\t[{accuracy_ci_lower:.2f}, {accuracy_ci_upper:.2f}]")
    print(f"Precision: {precision_medians:.2f}\t[{precision_ci_lower:.2f}, {precision_ci_upper:.2f}]")
    print(f"Recall   : {recall_medians:.2f}\t[{recall_ci_lower:.2f}, {recall_ci_upper:.2f}]")
    print(f"F1-score : {f1_medians:.2f}\t[{f1_ci_lower:.2f}, {f1_ci_upper:.2f}]")
    print(f"ROC AUC  : {auc_medians:.2f}\t[{auc_ci_lower:.2f}, {auc_ci_upper:.2f}]")

    print("\nConfusion matrix:")
    print(confusion_matrix(y_true, y_pred_medians))

    return {
        "accuracy_medians": accuracy_medians,
        "accuracy_lower": accuracy_ci_lower,
        "accuracy_upper": accuracy_ci_upper,
        "precision_medians": precision_medians,
        "precision_lower": precision_ci_lower,
        "precision_upper": precision_ci_upper,
        "recall_medians": recall_medians,
        "recall_lower": recall_ci_lower,
        "recall_upper": recall_ci_upper,
        "f1_medians": f1_medians,
        "f1_lower": f1_ci_lower,
        "f1_upper": f1_ci_upper,
        "auc_medians": auc_medians,
        "auc_lower": auc_ci_lower,
        "auc_upper": auc_ci_upper
    }

def plot_posterior_prediction_calibration_average(
        idata,
        by_item=None,
        only_global=False,
        n_bins = 10,
):
    # taking the mean over all chains and all draws

    y_pred_prob_dict, y_true_dict = {}, {}

    if np.isnan(idata.observed_data["y"].values).any():
        warnings.warn(
            "y_true data contains missing values; these data are excluded "
            "in both y_true and posterior predictions."
        )

    if by_item is None:
        y_pred_prob_dict["global"] = idata.posterior["p"].values[:,:,:,:,:].mean(axis=(0, 1), dtype=np.float64).ravel()
        y_true_dict["global"] = idata.observed_data["y"].values[:,:,:].ravel()
        
        nan_mask = np.isnan(y_true_dict["global"])
        y_pred_prob_dict["global"]  = y_pred_prob_dict["global"][~nan_mask]
        y_true_dict["global"]       = y_true_dict["global"][~nan_mask]

        if not only_global:
            for by_item in range(0, idata.posterior.sizes["item"]):
                y_pred_prob_dict[f"{by_item}"] = idata.posterior["p"].values[:,:,:,by_item,:].mean(axis=(0, 1), dtype=np.float64).ravel()
                y_true_dict[f"{by_item}"]      = idata.observed_data["y"].values[:,by_item,:].ravel()

                nan_mask = np.isnan(y_true_dict[f"{by_item}"])
                y_pred_prob_dict[f"{by_item}"] = y_pred_prob_dict[f"{by_item}"][~nan_mask]
                y_true_dict[f"{by_item}"]      = y_true_dict[f"{by_item}"][~nan_mask]

    else:
        y_pred_prob_dict[f"{by_item}"] = idata.posterior["p"].values[:,:,:,by_item,:].mean(axis=(0, 1), dtype=np.float64).ravel()
        y_true_dict[f"{by_item}"] = idata.observed_data["y"].values[:,by_item,:].ravel()

        nan_mask = np.isnan(y_true_dict[f"{by_item}"])
        y_pred_prob_dict[f"{by_item}"] = y_pred_prob_dict[f"{by_item}"][~nan_mask]
        y_true_dict[f"{by_item}"]      = y_true_dict[f"{by_item}"][~nan_mask]


    plt.figure(figsize=(6, 6))
    plt.plot([0, 1], [0, 1], "k--", label="Perfect calibration")

    item_names = idata.posterior["intercept"].coords["item"].values.tolist()

    for key in sorted(list(y_pred_prob_dict.keys())):
        # get quantile boundaries
        edges = np.quantile(y_pred_prob_dict[key], np.linspace(0, 1, n_bins + 1))
        # Remove duplicate edges (equivalent to duplicates="drop")
        edges = np.unique(edges)

        # Assign observations to bins
        bins = np.digitize(y_pred_prob_dict[key], edges[1:-1], right=True)

        pred_mean = []
        obs_rate = []
        counts = []

        for b in range(len(edges) - 1):
            mask = bins == b
            if np.any(mask):
                pred_mean.append(y_pred_prob_dict[key][mask].mean(dtype=np.float64))
                obs_rate.append(y_true_dict[key][mask].mean(dtype=np.float64))
                counts.append(mask.sum())

        pred_mean = np.asarray(pred_mean)
        obs_rate = np.asarray(obs_rate)
        counts = np.asarray(counts)

        plot_label = key
        if key.isdigit():
            plot_label = item_names[int(key)]
        
        plt.plot(pred_mean, obs_rate, "o-" if key == "global" else "x-", label=plot_label)
        

    plt.xlabel("Mean predicted probability")
    plt.ylabel("Observed proportion correct")
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.grid(alpha=0.3)
    plt.legend()

    plt.show()


def plot_posterior_prediction_calibration(
        idata,
        by_item=None,
        n_bins = 10,
):

    def posterior_prediction_calibration_distribution_by_item(
        y_pred_prob,
        y_true,
        n_bins,
        n_draws
    ):
        y_true_expanded = np.broadcast_to(y_true, (n_draws, len(y_true)))
        nan_mask = np.isnan(y_true_expanded).ravel()
        
        # get bin boundaries from quantiles instead of fixed bins, to
        # handle differing observation density across items
        edges = np.quantile(y_pred_prob[~nan_mask], np.linspace(0, 1, n_bins + 1))

        # Remove duplicate edges (equivalent to duplicates="drop")
        edges = np.unique(edges)

        # Assign observations to bins
        bin_assignment = np.digitize(y_pred_prob, edges[1:-1], right=True)

        # Make sure shape matches so we can chunk in draws properly
        chunk_size = len(bin_assignment) // n_draws

        if len(bin_assignment) != chunk_size * n_draws:
            raise RuntimeError("Array cannot be chunked correctly by draws")

        assignments_ = bin_assignment.reshape(n_draws, chunk_size)
        y_pred_prob_ = y_pred_prob.reshape(n_draws, chunk_size)

        if n_draws != assignments_.shape[0]:
            raise RuntimeError(f"Shapes do not match! n_draws: {n_draws} - chunks: {assignments_.shape[0]}")
        
        nan_mask = nan_mask.reshape(n_draws, chunk_size)

        result = []

        # For each bin calculate mean, ci_upper, ci_lower over all draws
        for bin in range(0, n_bins):
            bin_mask = assignments_ == bin
            selection_mask = bin_mask & ~nan_mask

            # skip bin if there was no valid assignment for that bin
            if not selection_mask.any():
                continue

            # careful: we are talking about means of means here
            # Note: all three posterior draws get an equal weight in the average
            draw_means = np.ma.array(y_pred_prob_, mask=~selection_mask).mean(axis=1, dtype=np.float64)

            # remove possibly masked entries if bins are omitted in a draw
            draw_means = draw_means.compressed()

            mean = np.mean(draw_means)
            variance = np.var(draw_means)

            # uncertainty in the posterior mean predicted
            # probability within each bin
            quantile_bounds = np.quantile(draw_means, [0.025, 0.975])

            mean_y_true = np.mean(y_true_expanded[selection_mask], dtype=np.float64)

            result.append({
                "y_pred": {
                    "mean": mean,
                    "variance": variance,
                    "ci_lower": quantile_bounds[0],
                    "ci_upper": quantile_bounds[1]                    
                },
                "y_true": {
                    "mean": mean_y_true
                }
            })

        return result


    item_names = idata.posterior["intercept"].coords["item"].values.tolist()
    bins_by_item = {}

    if by_item is not None:
        item_names = [by_item]

    n_draws = idata.posterior.coords["draw"].size
    chain_id = 0    # TODO: handle multiple chains

    for idx, item in tqdm(enumerate(item_names), total=len(item_names)):
        if by_item is not None:
            idx = idata.posterior["intercept"].coords["item"].values.tolist().index(by_item)
        y_pred_prob = idata.posterior["p"].values[chain_id,:,:,idx,:].ravel()
        y_true      = idata.observed_data["y"].values[:,idx,:].ravel()

        bins_by_item[item] = posterior_prediction_calibration_distribution_by_item(
            y_pred_prob,
            y_true,
            n_bins,
            n_draws
        )


    plt.figure(figsize=(6, 6))
    plt.plot([0, 1], [0, 1], "k--", label="Perfect calibration")

    for item in item_names:
        bin_results = bins_by_item[item]
        x = [bin["y_pred"]["mean"] for bin in bin_results] # Mean predicted probability
        y = [bin["y_true"]["mean"] for bin in bin_results] # Observed proportion correct
        plt.plot(x, y, "x-", label=item)

        # Plot confidence interval
        ci_lower = [bin["y_pred"]["ci_lower"] for bin in bin_results]
        ci_upper = [bin["y_pred"]["ci_upper"] for bin in bin_results]
        plt.fill_betweenx(
            y,
            ci_lower,
            ci_upper,
            alpha=0.2
        )

    plt.xlabel("Mean predicted probability")
    plt.ylabel("Observed proportion correct")
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()



from jax.nn import sigmoid

def get_predictions_from_samples_2PL(idata, posterior_samples):
    """
    Compute predicted probabilities from posterior parameter samples and add them to the passed idata.

    Logits are computed according to 2PL formula.

    The function supports posterior samples both with and without an explicit
    ``chain`` dimension. When a ``chain`` dimension is present, it is preserved
    in the output. Otherwise, a single chain dimension is added to the
    idata.posterior["p"]

    Parameters
    ----------
    posterior_samples : dict or xarray.DataTree
        Posterior samples containing the following parameters:

        ``theta``
            Latent trait samples with dimensions
            ``(draw, latent, person, time)`` or
            ``(chain, draw, latent, person, time)``.

        ``discrimination``
            Item discrimination parameters with dimensions
            ``(draw, latent, item)`` or
            ``(chain, draw, latent, item)``.

        ``b``
            Item difficulty parameters with dimensions
            ``(draw, item)`` or ``(chain, draw, item)``.

    Computes
    -------
    idata.posterior["p"]
        Predicted probabilities with dimensions
        ``(chain, draw, person, item, time)``. If the input does not contain
        a chain dimension, a singleton chain dimension is added to the output.

        Each value represents the predicted probability for a given person,
        item, and time point for a posterior sample.
    """

    posterior_preds = get_predictions_from_samples_2PL_(posterior_samples)

    idata.posterior["p"] =  xr.DataArray(
        posterior_preds,
        dims=("chain", "draw", "person", "item", "time"),
        coords={
            "chain": idata.posterior.coords["chain"],
            "draw": idata.posterior.coords["draw"],
            "person": idata.posterior.coords["person"],
            "item": idata.posterior.coords["item"],
            "time": idata.posterior.coords["time"]
        }
    )

def get_predictions_from_samples_2PL_(posterior_samples):
    
    # (draw, latent, person, time)
    theta = posterior_samples["theta"]

    # (draw, latent, item)
    discrimination = posterior_samples["discrimination"]

    # (draw, item)
    difficulty = posterior_samples["b"]

    if isinstance(posterior_samples, xr.DataTree):
        # (draw, item)
        difficulty = posterior_samples["b"].values


    if not isinstance(posterior_samples, xr.DataTree) or not "chain" in posterior_samples["theta"].coords:
        latent_effect = None
        difficulty_expanded = None
        logits = None
        if len(posterior_samples["theta"].shape) == 4 and len(discrimination.shape) == 3:
            # yields (draw, person, item, time)
            latent_effect = np.einsum(
                "dli,dlpt->dpit",
                discrimination,
                theta
            )

            # yields (draw, person, item, time)
            difficulty_expanded = difficulty[:, None, :, None]

            logits = latent_effect - difficulty_expanded
        elif len(posterior_samples["theta"].shape) == 3 and len(discrimination.shape) == 2:
            # yields (person, item, time)
            latent_effect = np.einsum(
                "li,lpt->pit",
                discrimination,
                theta
            )

            # yields (person, item, time)
            difficulty_expanded = difficulty[None, :, None]

            logits = latent_effect - difficulty_expanded
            # add a "fake" draw
            logits = logits[None, :,:,:]

        # return (chain, draw, person, item, time)
        return sigmoid(logits)[None, :, :, :, :]

    if isinstance(posterior_samples, xr.DataTree) and "chain" in posterior_samples["theta"].coords:
        # yields (chain, draw, person, item, time)
        latent_effect = np.einsum(
            "cdli,cdlpt->cdpit",
            discrimination,
            theta
        )

        # yields (chain, draw, person, item, time)
        difficulty_expanded = difficulty[:, :, None, :, None]

        logits = latent_effect - difficulty_expanded

        # return (chain, draw, person, item, time)
        return sigmoid(logits)

    raise ValueError("`posterior_samples` have to be xr.DataTree with chain dimension or a raw array without chain dimension")


def sample_from_svi(guide, svi_result_params, n_draws, rng_key=None):
    return guide.sample_posterior(
        rng_key, svi_result_params, sample_shape=(n_draws,)
    )


def plot_posterior_prediction_calibration_from_svi_params(
        posterior_medians,
        posterior_quantiles,
        y_true, # (person, item, time)
        item_names = None,
        n_bins = 10
):

    # (chain, draw, person, item, time)
    # yields (person, item, time)
    y_pred_probs_medians = get_predictions_from_samples_2PL_(posterior_medians)[0][0]

    # (chain, draw, person, item, time)
    # yields (person, item, time)
    y_pred_probs_ci_lower = get_predictions_from_samples_2PL_(
            {k: v[0] for k,v in posterior_quantiles.items()}
        )[0][0]

    y_pred_probs_ci_upper = get_predictions_from_samples_2PL_(
            {k: v[1] for k,v in posterior_quantiles.items()}
        )[0][0]

    if item_names is None:
        item_names = [f"item {i}" for i in range(0, posterior_medians["discrimination"].shape[1])]
    bins_by_item = {k: [] for k in item_names}

    for idx, item in tqdm(enumerate(item_names), total=len(item_names)):
        nan_mask = np.isnan(y_true[:,idx,:]).ravel()

        # get bin boundaries from quantiles instead of fixed bins, to
        # handle differing observation density across items
        edges = np.quantile(y_pred_probs_medians[:,idx,:].ravel()[~nan_mask], np.linspace(0, 1, n_bins + 1))

        # Remove duplicate edges (equivalent to duplicates="drop")
        edges = np.unique(edges)

        # Assign observations to bins
        bin_assignment = np.digitize(y_pred_probs_medians[:,idx,:].ravel(), edges[1:-1], right=True)

        for bin in range(0, n_bins):
            bin_mask = bin_assignment == bin
            selection_mask = bin_mask & ~nan_mask

            # skip bin if there was no valid assignment for that bin
            if not selection_mask.any():
                continue

            bin_mean_y_true = np.mean(y_true[:,idx,:].ravel()[selection_mask], dtype=np.float64)
            bin_mean_y_pred_prob_medians = np.mean(y_pred_probs_medians[:,idx,:].ravel()[selection_mask], dtype=np.float64)
            bin_mean_y_pred_prob_ci_upper = np.mean(y_pred_probs_ci_lower[:,idx,:].ravel()[selection_mask], dtype=np.float64)
            bin_mean_y_pred_prob_ci_lower = np.mean(y_pred_probs_ci_upper[:,idx,:].ravel()[selection_mask], dtype=np.float64)

            bins_by_item[item].append({
                "y_pred": {
                    "mean": bin_mean_y_pred_prob_medians,
                    "ci_lower": bin_mean_y_pred_prob_ci_upper,
                    "ci_upper": bin_mean_y_pred_prob_ci_lower
                },
                "y_true": {
                    "mean": bin_mean_y_true
                }
            })

    print("! Note !\n--------\n`lower` and `upper` bounds are defined by lower and upper",
              "bounds of the model parameters not the posterior predictions.")

    plt.figure(figsize=(6, 6))
    plt.plot([0, 1], [0, 1], "k--", label="Perfect calibration")


    for item in item_names:
        bin_results = bins_by_item[item]
        x = [bin["y_pred"]["mean"] for bin in bin_results] # Mean predicted probability
        y = [bin["y_true"]["mean"] for bin in bin_results] # Observed proportion correct
        plt.plot(x, y, "x-", label=item)

        # Plot confidence interval
        ci_lower = [bin["y_pred"]["ci_lower"] for bin in bin_results]
        ci_upper = [bin["y_pred"]["ci_upper"] for bin in bin_results]
        plt.fill_betweenx(
            y,
            ci_lower,
            ci_upper,
            alpha=0.2
        )

    plt.xlabel("Mean predicted probability")
    plt.ylabel("Observed proportion correct")
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()